### ISSUE TITLE
Service is running in background after apk was closed

### ISSUE THREAD

**Issue by agilob** [wish7code/openbmap#110]
After closing radiobeacon and uploading data service is still running.

You can see it running in `OS monitor` (available in F-droid)

Status is sleeping, but I still think it should be stopped completely to free memory (~20MB).

**Comment by gdt** [comment]
Perhaps this is related to #105.

**Comment by agilob** [comment]
Yup, most probably a duplicate!

**Comment by gdt** [comment]
I wouldn't say duplicate.  Android has notions about leaving things running, and the rule is more or less that they shouldn't consume resources, vs not be running.   This is unsettling to old-school types.    You say "closing", but that really just means not having the Activity that represents the status screen active.
The OS will free memory when it is needed.  Unless it has set foreground priority which it shouldn't :-)

However, I could certainly appreciate a scheme where the service is terminated when it isn't needed, and would prefer that too.   It would be good to find the issue causing #105 first, and after that's debugged to have this issue resolved.

**Comment by wish7code** [comment]
Hey guys!

Sorry for my late reply: just back from holydays.. Guess currently the service part is currently over-engineered, causing issues as described above;-)

Next release will have a simpler service architecture, meaning a simple 'master service' which coordinate all the other services (i.e. wireless logger service, positioning service and gpx logger service). I was also thinking of using a dedicated event bus (e.g. https://github.com/greenrobot/EventBus) instead of home-brewn inter-service communication..

Cheers
Toby
