### ISSUE TITLE
Settle on case convention for wifis between Radiobeacon and NLP

### ISSUE THREAD

**Issue by mvglasow** [wish7code/openbmap#133]
Wifi catalog lookups by BSSID are case-sensitive and Radiobeacon currently seems to default to lowercase when comparing scanned wifis to those in the database, or when syncing the wifi catalog locally.

Unfortunately the location provider seems to default to uppercase: the downloaded Wifi catalog has uppercase BSSIDs, and the NLP seems to use uppercase for (offline) database lookups.

That makes it impossible to share the wifi catalog between UnifiedNLP and Radiobeacon: Radiobeacon will report wifis as new even though they are in the catalog, and UnifiedNLP will not find wifis which were synced locally with Radiobeacon. The difference in case is the only thing that prevents this from working. (Test: I process my own wifi catalog, until now using uppercase. OpenNLP could use it but Radiobeacon would report almost all wifis as new. After I switched to lowercase, Radiobeacon would recognize wifis from the catalog and no longer count them as new, but the NLP would no longer find any wifis.)

The easiest fix in terms of compatibility is probably to change Radiobeacon in the following way:
* Use both uppercase and lowercase on lookup (`SELECT * FROM wifi_zone WHERE bssid=UPPER(?) OR bssid = LOWER(?)`)
* Write uppercase BSSIDs on sync
* At the start of each sync, convert any lowercase BSSIDs to uppercase

This would work with any catalog downloaded until now, and also with newly synced wifis. Only wifis synced locally with an earlier version of Radiobeacon would not be usable by the NLP until the first sync is carried out.

**Comment by gdt** [comment]
It seems that BSSID values are actually in hex, and in the Unix tradition I would expect the proper represnentation to be lower case.    Certainly looking up in a case-insensitive manner sounds good.  Can you comment about other catalogs, and if there is a wel-established convention?

**Comment by mvglasow** [comment]
@gdt yes, a BSSID is actually a MAC address, that is, 48 bits in hex.

The only other catalog that I know of is openwlanmap.org, and they seem to use all-uppercase as well. I am not aware of any convention regarding case that ould apply here.

The reason I'm suggesting uppercase it that it is the format currently used by the downloadable wifi catalog. Switching would make the new catalog incompatible with older versions of the NLP (as of now, the NLP doesn't recognize lowercase – I've tested it).

**Comment by gdt** [comment]
If the preponderance of choice is upper, that sounds fine.  I was just meaning to suggest checking others.   And I certainly agree this should be consistent.

**Comment by wish7code** [comment]
Excellent! Thanks for tracing this issue down!

Some time ago, we thought it might be a good idea to change the unifiedNlp provider (online as well as offline) to uppercase: guess that's the default for all major geolocation APIs (Google, Firefox and Apple and the like). So by now we should have improved compatibility. Unfortunately we forgot to adjust the local sync feature Radiobeacon, which defaults to lowercase.

As a first fix I made Radiobeacon default to uppercase in the future. As a second quickfix server-side templates have been made case-insensitive (https://stackoverflow.com/questions/973541/how-to-set-sqlite3-to-be-case-insensitive-when-string-comparing)

We're left with the problem that any previously synced wifi catalog still won't work.
I guess a 'UPDATE wifi_zone SET bssid = UPPER(bssid)' would fix that.

Since I know (and highly appreciate) both of you as power-users, would that do the fix?

**Comment by mvglasow** [comment]
Yep, that statement definitely fixes it (I'd processed myself an all-lowercase wifi catalog, which didn't work with the NLP, and that statement fixed it).

In Radiobeacon, fixes needs to be applied in two places: write uppercase BSSIDs when syncing the wifi catalog locally, and doing a case-insensitive match when comparing scanned wifis to the catalog (to find out if we have a new wifi).

**Comment by mvglasow** [comment]
Did some logging with the new version, and stats look OK (I get only a handful of new wifis in an area I have previously surveyed). I'd say it's fixed.
